# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: repopsy

before:
  hooks:
    - go mod tidy

builds:
  - id: repopsy
    main: .
    binary: repopsy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"

brews:
  - name: repopsy
    repository:
      owner: andpalmier
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/andpalmier/repopsy"
    description: "Forensic tool for analyzing git repository history"
    license: "AGPL-3.0"
    test: |
      system "#{bin}/repopsy --version"

dockers:
  - image_templates:
      - "ghcr.io/andpalmier/repopsy:{{ .Version }}-amd64"
      - "ghcr.io/andpalmier/repopsy:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - internal
      - cmd
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Git repository forensic expander"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/andpalmier/repopsy"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0"

  - image_templates:
      - "ghcr.io/andpalmier/repopsy:{{ .Version }}-arm64"
      - "ghcr.io/andpalmier/repopsy:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - internal
      - cmd
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Git repository forensic expander"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/andpalmier/repopsy"
      - "--label=org.opencontainers.image.licenses=AGPL-3.0"

docker_manifests:
  - name_template: "ghcr.io/andpalmier/repopsy:{{ .Version }}"
    image_templates:
      - "ghcr.io/andpalmier/repopsy:{{ .Version }}-amd64"
      - "ghcr.io/andpalmier/repopsy:{{ .Version }}-arm64"
  - name_template: "ghcr.io/andpalmier/repopsy:latest"
    image_templates:
      - "ghcr.io/andpalmier/repopsy:latest-amd64"
      - "ghcr.io/andpalmier/repopsy:latest-arm64"

release:
  github:
    owner: andpalmier
    name: repopsy
  draft: false
  prerelease: auto
